services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  ProjetNormandie\ForumBundle\Controller\Forum\Home:
    arguments:
      - '@pn.forum.handler.user_data_init'
      - '@doctrine.orm.entity_manager'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\ForumBundle\Controller\Forum\ReadAll:
    arguments:
      - '@pn.forum.handler.mark_as_read'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\ForumBundle\Controller\Forum\Read:
    arguments:
      - '@pn.forum.handler.mark_as_read'
    calls:
      - [ setContainer, [ "@service_container" ] ]
