services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  ProjetNormandie\ForumBundle\Controller\Forum\Home:
    arguments:
      - '@doctrine.orm.entity_manager'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\ForumBundle\Controller\Forum\ReadAll:
    arguments:
      - '@doctrine.orm.entity_manager'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\ForumBundle\Controller\Forum\Read:
    arguments:
      - '@doctrine.orm.entity_manager'
    calls:
      - [ setContainer, [ "@service_container" ] ]
