services:
    sonata.admin.forum.category:
        class: ProjetNormandie\ForumBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ForumBundle", label: "Category" }
        arguments:
            - ~
            - ProjetNormandie\ForumBundle\Entity\Category
            - ~
    sonata.admin.forum.forum:
        class: ProjetNormandie\ForumBundle\Admin\ForumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ForumBundle", label: "Forum" }
        arguments:
            - ~
            - ProjetNormandie\ForumBundle\Entity\Forum
            - ~
    sonata.admin.forum.topic:
        class: ProjetNormandie\ForumBundle\Admin\TopicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ForumBundle", label: "Topic" }
        arguments:
            - ~
            - ProjetNormandie\ForumBundle\Entity\Topic
            - ~
    sonata.admin.forum.message:
        class: ProjetNormandie\ForumBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ForumBundle", label: "Message" }
        arguments:
            - ~
            - ProjetNormandie\ForumBundle\Entity\Message
            - ~

