resources:
    ProjetNormandie\ForumBundle\Entity\Category:
        collectionOperations:
            get: ~
            home:
                method: 'GET'
                normalization_context: {'groups': [category_read, forum_read, message_read, user_read]}
                path: '/categorie/home'
                controller: 'ProjetNormandie\ForumBundle\Controller\CategoryController::home'
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\Forum:
        collectionOperations:
            get: ~
        itemOperations:
            get:
                normalization_context: {'groups': [forum_read]}
                access_control: 'object.getStatus() == "public" or is_granted(object.getRole())'
        properties:
            topics:
                subresource:
                    resourceClass: 'ProjetNormandie\ForumBundle\Entity\Topic'
                    maxDepth: 1
                    collection: false
    ProjetNormandie\ForumBundle\Entity\Topic:
        attributes:
            pagination_items_per_page: 20
#            order:
#                - 'lastMessage.id'
        collectionOperations:
            get:
                normalization_context: {'groups': [topic_read, message_read, user_read]}
                access_control: 'object.getForum().getStatus() == "public" or is_granted(object.getForum().getRole())'
            api_forums_topics_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [topic_read, message_read, user_read]}
            post:
                access_control: 'is_granted("ROLE_USER")'
                denormalization_context: {'groups': [topic_post]}
        itemOperations:
            get:
                normalization_context: {'groups': [topic_read, forum_read]}
            put:
                access_control: 'is_granted("ROLE_USER") and object.getUser() == user'
        properties:
            messages:
                subresource:
                    resourceClass: 'ProjetNormandie\ForumBundle\Entity\Message'
                    collection: true
    ProjetNormandie\ForumBundle\Entity\TopicType:
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\TopicUser:
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\Language:
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\Message:
        attributes:
            pagination_items_per_page: 20
            filters: ['forum_message.order_filter']
        collectionOperations:
            get:
                normalization_context: {'groups': [message_read]}
            post: ~
            api_topics_messages_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [message_read]}
        itemOperations:
            get:
                normalization_context: {'groups': [message_read]}
            put:
                access_control: 'is_granted("ROLE_USER") and object.getUser() == user'
                denormalization_context: {'groups': [message_put]}

