resources:
    ProjetNormandie\ForumBundle\Entity\Category:
        collectionOperations:
            get: ~
            home:
                method: 'GET'
                normalization_context: {'groups': [forum_home, forum_list]}
                path: '/categorie/home'
                controller: 'ProjetNormandie\ForumBundle\Controller\CategoryController::home'
        itemOperations:
            get: ~
            forums-father:
                method: 'GET'
                path: '/categorie/{id}/forums-father'
                controller: 'ProjetNormandie\ForumBundle\Controller\CategoryController::forumFather'

    ProjetNormandie\ForumBundle\Entity\Forum:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
        properties:
            topics:
                subresource:
                    resourceClass: 'ProjetNormandie\ForumBundle\Entity\Topic'
                    maxDepth: 1
                    collection: false
    ProjetNormandie\ForumBundle\Entity\Topic:
        attributes:
            pagination_items_per_page: 20
#            order:
#                - 'lastMessage.id'
        collectionOperations:
            get:
                normalization_context: {'groups': [topic_list]}
            api_forums_topics_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [topic_list]}
        itemOperations:
            get: ~
        properties:
            messages:
                subresource:
                    resourceClass: 'ProjetNormandie\ForumBundle\Entity\Message'
                    collection: false
    ProjetNormandie\ForumBundle\Entity\Message:
        attributes:
            pagination_items_per_page: 20
        collectionOperations:
            get: ~
            api_topics_messages_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [message_list]}
        itemOperations:
            get: ~
            put: ~

