resources:
    ProjetNormandie\ForumBundle\Entity\Category:
        collectionOperations:
            get: ~
            home:
                method: 'GET'
                normalization_context: {'groups': [forum_home]}
                path: '/categorie/home'
                controller: 'ProjetNormandie\ForumBundle\Controller\CategoryController::home'
        itemOperations:
            get: ~
            forums-father:
                method: 'GET'
                path: '/categorie/{id}/forums-father'
                controller: 'ProjetNormandie\ForumBundle\Controller\CategoryController::forumFather'
    ProjetNormandie\ForumBundle\Entity\Forum:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\Topic:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    ProjetNormandie\ForumBundle\Entity\Message:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
