ProjetNormandie\ForumBundle\Entity\Forum:
  attributes:
    id:
      groups:
        - 'forum.forum.read'
    libForum:
      groups:
        - 'forum.forum.read'
    slug:
      groups:
        - 'forum.forum.read'
    status:
      groups:
        - 'forum.forum.read'
    category:
      groups: []
    position:
      groups: []
    nbTopic:
      groups:
        - 'forum.forum.read'
    nbMessage:
      groups:
        - 'forum.forum.read'
    lastMessage:
      groups:
        - 'forum.lastMessage'
    forumUser:
      groups:
        - 'forum.user.read'
    createdAt:
      groups: []
    updatedAt:
      groups: []
