ProjetNormandie\ForumBundle\Entity\Forum:
  attributes:
    id:
      groups:
        - 'forum_read'
    libForum:
      groups:
        - 'forum_read'
    category:
      groups: []
    position:
      groups: []
    nbTopic:
      groups:
        - 'forum_read'
    nbMessage:
      groups:
        - 'forum_read'
    lastMessage:
      groups:
        - 'forum_read'
    forumUser:
      groups:
        - 'forum_user_read'
    createdAt:
      groups: []
    updatedAt:
      groups: []
