ProjetNormandie\ForumBundle\Entity\Forum:
  attributes:
    id:
      groups:
        - 'forum_list'
    libForum:
      groups:
        - 'forum_list'
    category:
      groups: []
    position:
      groups: []
    nbTopic:
      groups:
        - 'forum_list'
    nbMessage:
      groups:
        - 'forum_list'
    lastMessage:
      groups:
        - 'forum_list'
    createdAt:
      groups: []
    updatedAt:
      groups: []
