ProjetNormandie\ForumBundle\Entity\Message:
  attributes:
    id:
      groups:
        - 'forum.message.read'
        - 'forum.message.put'
        - 'message.last'
    user:
      groups:
        - 'forum.message.read'
        - 'forum.topic.post'
        - 'message.last'
    topic:
      groups: []
    message:
      groups:
        - 'forum.message.read'
        - 'forum.message.put'
        - 'forum.topic.post'
    createdAt:
      groups:
        - 'forum.message.read'
        - 'message.last'
    updatedAt:
      groups:
        - 'forum.message.read'
