ProjetNormandie\ForumBundle\Entity\Message:
  attributes:
    id:
      groups:
        - 'message_read'
        - 'message_put'
    user:
      groups:
        - 'message_read'
        - 'topic_post'
    topic:
      groups: []
    message:
      groups:
        - 'message_read'
        - 'message_put'
        - 'topic_post'
    createdAt:
      groups:
        - 'message_read'
    updatedAt:
      groups:
        - 'message_read'
