ProjetNormandie\ForumBundle\Entity\Message:
  attributes:
    id:
      groups:
        - 'forum_list'
        - 'topic_list'
        - 'message_list'
    user:
      groups:
        - 'forum_list'
        - 'topic_list'
        - 'message_list'
    topic:
      groups: []
    message:
      groups:
        - 'message_list'
    createdAt:
      groups:
        - 'forum_list'
        - 'topic_list'
        - 'message_list'
    updatedAt:
      groups:
        - 'message_list'
