ProjetNormandie\ForumBundle\Entity\Topic:
  attributes:
    id:
      groups:
        - 'forum.topic.read'
    forum:
      groups:
        - 'forum.topic.read'
        - 'forum.topic.post'
    libTopic:
      groups:
        - 'forum.topic.read'
        - 'forum.topic.post'
    slug:
      groups:
        - 'forum.topic.read'
    type:
      groups:
        - 'forum.topic.read'
        - 'forum.topic.post'
    nbMessage:
      groups:
        - 'forum.topic.read'
    user:
      groups:
        - 'forum.topic.read'
    topicUser1:
      groups:
        - 'forum.topic.user.read'
    lastMessage:
      groups:
        - 'forum.topic.lastMessage'
    messages:
      groups:
        - 'forum.topic.post'
    createdAt:
      groups: []
    updatedAt:
      groups: []
