ProjetNormandie\ForumBundle\Entity\Topic:
  attributes:
    id:
      groups:
        - 'forum_list'
        - 'topic_list'
    libTopic:
      groups:
        - 'topic_list'
    type:
      groups: []
    nbMessage:
      groups:
        - 'forum_list'
        - 'topic_list'
    user:
      groups:
        - 'forum_list'
        - 'topic_list'
    lastMessage:
      groups:
        - 'topic_list'
    messages:
      groups: []
    createdAt:
      groups: []
    updatedAt:
      groups: []
