ProjetNormandie\ForumBundle\Entity\Topic:
  attributes:
    id:
      groups:
        - 'topic_read'
    forum:
      groups:
        - 'forum_read'
        - 'topic_post'
    libTopic:
      groups:
        - 'topic_read'
        - 'topic_post'
    type:
      groups:
        - 'topic_post'
    nbMessage:
      groups:
        - 'topic_read'
    user:
      groups:
        - 'topic_read'
        - 'topic_post'
    language:
      groups:
        - 'topic_post'
    lastMessage:
      groups:
        - 'topic_read'
    messages:
      groups:
        - 'topic_post'
    createdAt:
      groups: []
    updatedAt:
      groups: []
