ProjetNormandie\ForumBundle\Entity\TopicUser:
  attributes:
    id:
      groups:
        - 'forum.topic.user.read'
        - 'forum.topic.user.put'
    user:
      groups: []
    topic:
      groups: []
    boolRead:
      groups:
        - 'forum.topic.user.read'
    boolNotif:
      groups:
        - 'forum.topic.user.read'
        - 'forum.topic.user.put'
