App\Entity\User:
  attributes:
    id:
      groups:
        - 'forum_list'
        - 'topic_list'
        - 'message_list'
    username:
      groups:
        - 'forum_list'
        - 'topic_list'
        - 'message_list'

