ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'forum.user.read'
    username:
      groups:
        - 'forum.user.read'
    avatar:
      groups:
        - 'forum.user.read'
    slug:
      groups:
        - 'forum.user.read'
    status:
      groups:
        - 'forum.user.status'
    nbForumMessage:
      groups:
        - 'forum.user.read'
    isOnline:
      groups:
        - 'forum.user.read'

