ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'user.read'
    username:
      groups:
        - 'user.read'
    avatar:
      groups:
        - 'user.read'
    slug:
      groups:
        - 'user.read'
    nbForumMessage:
      groups:
        - 'user.read'

