services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ProjetNormandie\ForumBundle\Serializer\TopicContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@ProjetNormandie\ForumBundle\Serializer\TopicContextBuilder.inner'
            - '@security.authorization_checker'
        autoconfigure: false
    ProjetNormandie\ForumBundle\Serializer\ForumContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
             - '@ProjetNormandie\ForumBundle\Serializer\ForumContextBuilder.inner'
             - '@security.authorization_checker'
        autoconfigure: false

    # Handlers
    pn.forum.handler.user_data_init:
        class: ProjetNormandie\ForumBundle\Handler\UserDataInitHandler
        arguments:
            - '@doctrine.orm.entity_manager'


    pn.forum.handler.mark_as_not_read:
        class: ProjetNormandie\ForumBundle\Service\MarkAsNotReadService
        arguments:
            - '@security.helper'
            - '@doctrine.orm.entity_manager'

    pn.forum.handler.mark_as_read:
        class: ProjetNormandie\ForumBundle\Service\MarkAsReadService
        arguments:
            - '@security.helper'
            - '@pn.bundle.repository.forum_user'
            - '@pn.bundle.repository.topic_user'

    ProjetNormandie\ForumBundle\EventListener\Service\TopicService:
        class: ProjetNormandie\ForumBundle\EventListener\Service\TopicService
        arguments:
            - '@doctrine.orm.entity_manager'
