services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\ForumBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  ProjetNormandie\ForumBundle\Serializer\ForumContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    autoconfigure: false

  pn.forum.event.entity.message:
    class: ProjetNormandie\ForumBundle\EventListener\Entity\MessageListener
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.event.entity.topic:
    class: ProjetNormandie\ForumBundle\EventListener\Entity\TopicListener
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.event.entity.forum:
    class: ProjetNormandie\ForumBundle\EventListener\Entity\ForumListener
    tags:
      - { name: doctrine.orm.entity_listener }

