ProjetNormandie\ForumBundle\Entity\Category:
  attributes:
    id:
      groups:
        - 'forum.category.read'
    libCategory:
      groups:
        - 'forum.category.read'
    forums:
      groups:
        - 'forum.category.read'
    position:
      groups: []
    createdAt:
      groups: []
    updatedAt:
      groups: []
