ProjetNormandie\ForumBundle\Entity\ForumUser:
  attributes:
    id:
      groups:
        - 'forum.forumUser.read'
    user:
      groups: []
    forum:
      groups: []
    boolRead:
      groups:
        - 'forum.forumUser.read'
